### PR TITLE
breaking change for IRegistrationSorter.

### PR DESCRIPTION
**Pull request by bmcdavid**
added dependentregistrationfactory.
added customlifecycle to dependent registration.
added action for episerver to modify registrations.

### CODE REVIEW

**Comment by bmcdavid** [comment]
@valdisiljuconoks I added a custom lifecycle on dependent registrations shownhere:

https://github.com/bmcdavid/DotNetStarter.Extensions.Registrations/blob/feature/enhancements/tests/DotNetStarter.Extensions.Registrations.Core.Tests/DependentRegistrationTests.cs#L12-L28

For netcore I didn't bother adding in an action to modify lifecycle as that can be done after extension on the service collection.

For epi, I added an Action<ICollection<DependentRegistration>> argument where app owners can change discovered registrations.

Still thinking through registering dependencies in other assemblies that a package may reference.
My current thought is something like

```cs
[assembly: ExternalRegistration(typeof(ExternalClassAbstract),typeof(ExternalClassImpl),Lifecycle)] 
 // allowing multiple attributes for more registrations
```

Thoughts?

**Comment by valdisiljuconoks** [comment]
still thinking what is benefit with `assembly` level "attributes" vs custom lambda expressions somewhere to instruct scanner to look for X assemblies.

for instance, I like the way how structuremap registries and scanners are working - whole ceremony is done in code via fluent api (or almost fluent).

it opens up a bit more possibilities - like conditional discovered (like: based on X factor in this case I don't need to scan and look at assembly Y).

**Comment by bmcdavid** [comment]
My thinking is to not get involved in type creation and to get through process as quickly as possible. To me its easier to get attributes from the assembly than to scan for another thing (attribute or interface) implementation to get types that want to participate extending registrations, and then once I have the types, having to create instances of them.

I'll look through structuremap to see if I find some better inspiration. 

Thanks again for helping in this.

**Comment by bmcdavid** [comment]
How about having classes with an attribute with same base type as registration attr, that takes a string method name. If string is null, it can default to ‘configure’ or something. I can store that in something similar to dependent registration. 

The only catch is method has to be static and have an Action<configurationexpression> argument.

I won’t have to do any extra scanning or type creation, just use reflection to invoke the discovered types static method.

Also still need to work out what’s available in the configurationexpression object as well. Thinking of Add/Remove methods and assemblies property for ones used in discovery.

**Comment by bmcdavid** [comment]
@valdisiljuconoks How about this for registering externals:

https://github.com/bmcdavid/DotNetStarter.Extensions.Registrations/blob/feature/enhancements/tests/DotNetStarter.Extensions.Registrations.Core.Tests/Mocks/MockRegistrations.cs#L15-L22

where the configuration object is:
https://github.com/bmcdavid/DotNetStarter.Extensions.Registrations/blob/feature/enhancements/src/DotNetStarter.Extensions.Registrations/DependencyConfigurationExpression.cs

At first I had a remove method, but thought that package authors shouldn't have that control, only adding.

Also still thinking through where the attribute and configuration expression object should probably be located, in the extension package or the registration abstraction package.

**Comment by valdisiljuconoks** [comment]
looks good. I would leave it in extensions package for now

**Comment by bmcdavid** [comment]
@valdisiljuconoks Thanks for the feedback on this, updated versions will be pushed to NuGet shortly.

**Pull request merged**
